version: '3.1'  
services:  
  trsp-wg-vpn:
    build: ./build/wg-vpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    #  - SYS_MODULE
    environment:
      - WG_SERVERPORT=51820 
      - WG_PEERS=5 
      - WG_ALLOWEDIPS=0.0.0.0/0 
      - ANZ_REBUILD_CONFIG="no"
      - ANZ_RESOLVE_NXDOMAIN="no"
      - ANZ_DISABLED="no"
      #- DNSMAP_DNS_UPSTREAM="1.1.1.1:53"

    volumes:
    # - /lib/modules:/lib/modules
      - wireguard_config:/opt/wireguard/config
      - knot_db:/var/lib/knot-resolver/storage
      - knot_aliases:/etc/knot-resolver/aliases
      - antizapret_config:/opt/antizapret/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - 0.0.0.0:51820:51820/udp
volumes:
  wireguard_config:
  knot_db:
  knot_aliases:
  antizapret_config:
